# Generated by Django 5.0.3 on 2024-03-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_accepted',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
