# Generated by Django 5.0.3 on 2024-03-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetclinicuser',
            name='is_clerk',
            field=models.BooleanField(default=False, verbose_name='clerk status'),
        ),
        migrations.AddField(
            model_name='vetclinicuser',
            name='is_doctor',
            field=models.BooleanField(default=False, verbose_name='doctor status'),
        ),
    ]
