# Generated by Django 5.0.3 on 2024-03-23 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_vetclinicuser_is_clerk_vetclinicuser_is_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vetclinicuser',
            name='is_clerk',
        ),
    ]
