# Generated by Django 5.0.3 on 2024-03-24 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_patients', '0005_alter_petpatient_species_delete_species'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
